/*
  # Populate Sparse Categories with Listings

  1. New Listings
    - Catering & Private Chef: 5 listings (personal chefs and catering services)
    - Private Drivers: 4 listings (transfer and chauffeur services)
    - Grocery & Delivery: 4 listings (grocery stores and delivery services)
    - Natural & Organic Shops: 3 listings (health food and organic stores)
    - Eye Care: 3 listings (opticians and eye clinics)
    - Pediatric Care: 3 listings (children's doctors and clinics)
    - Boutiques & Fashion: 5 listings (clothing stores and designer boutiques)
    - Language Academies: 3 listings (Spanish, German, and multi-language schools)
    - Pool & Garden: 4 additional listings (pool maintenance, landscaping)

  2. Total: 34 new listings across 9 subcategories
*/

INSERT INTO listings (name, description, contact_phone, website_url, address, neighborhood, price_range, is_featured, category_id, tags, social_media)
VALUES
-- Catering & Private Chef
('Chef Marco Private Dining', 'Award-winning Italian chef offering bespoke private dining experiences in your villa or yacht. Specialises in Mediterranean fusion with locally sourced Mallorcan ingredients.', '+34 671 234 567', 'https://chefmarco.es', 'Available across Calvia', 'Santa Ponsa', '$$$$', true, 'b2000000-0000-0000-0000-000000000008', ARRAY['private-chef', 'italian', 'villa-dining', 'events'], '{"instagram": "https://instagram.com/chefmarcopalma"}'),
('Mallorca Catering Co.', 'Full-service catering for weddings, corporate events, and private parties. Mediterranean and international menus. Venue styling and staff included.', '+34 971 234 890', 'https://mallorcacatering.com', 'Calle del Puerto 14, Portals Nous', 'Portals Nous', '$$$', true, 'b2000000-0000-0000-0000-000000000008', ARRAY['catering', 'weddings', 'events', 'corporate'], NULL),
('La Table Privee', 'French-trained chef bringing Parisian elegance to your Mallorcan home. Multi-course tasting menus, wine pairing, and intimate dinner parties for up to 20 guests.', '+34 654 321 987', NULL, 'Available across Calvia', 'Bendinat', '$$$$', false, 'b2000000-0000-0000-0000-000000000008', ARRAY['french', 'tasting-menu', 'wine-pairing', 'private-dining'], '{"instagram": "https://instagram.com/latableprivee"}'),
('Sunny BBQ Mallorca', 'Professional BBQ and asado specialists for pool parties and garden events. Premium meats, seafood platters, and vegetarian options. Equipment and staff provided.', '+34 612 456 789', NULL, 'Available across Southwest Mallorca', 'Calvia Village', '$$', false, 'b2000000-0000-0000-0000-000000000008', ARRAY['bbq', 'pool-party', 'asado', 'outdoor-dining'], '{"instagram": "https://instagram.com/sunnybbqmallorca"}'),
('Villa Chef Mallorca', 'Daily or weekly private chef service for holiday villas. Breakfast, lunch, and dinner prepared fresh. Grocery shopping and meal prep included. Multiple cuisine styles.', '+34 678 901 234', 'https://villachefmallorca.com', 'Available across Calvia', 'Sol de Mallorca', '$$$', false, 'b2000000-0000-0000-0000-000000000008', ARRAY['private-chef', 'villa', 'weekly', 'meal-prep'], NULL),

-- Private Drivers
('Mallorca VIP Transfers', 'Premium airport transfers and island-wide chauffeur service. Mercedes fleet. Meet and greet at Palma airport, hotel pickups, and day excursions. 24/7 availability.', '+34 971 678 234', 'https://mallorcaviptransfers.com', 'Palma Airport / Calvia', 'Palmanova', '$$$', true, 'b4000000-0000-0000-0000-000000000001', ARRAY['airport-transfer', 'chauffeur', 'mercedes', 'vip'], NULL),
('Costa Transfers', 'Reliable and affordable transfers across Mallorca. Airport pickups, port transfers, golf course shuttles, and restaurant drop-offs. Clean, modern vehicles.', '+34 666 789 012', 'https://costatransfers.es', 'Avenida de la Playa 3, Magaluf', 'Magaluf', '$$', false, 'b4000000-0000-0000-0000-000000000001', ARRAY['airport', 'taxi', 'transfer', 'golf-shuttle'], NULL),
('Island Drive Mallorca', 'Luxury chauffeur service with multilingual drivers. Full-day island tours, wine route excursions, and VIP event transport. Tesla and BMW fleet.', '+34 634 567 890', 'https://islanddrivemallorca.com', 'Available across Mallorca', 'Santa Ponsa', '$$$$', false, 'b4000000-0000-0000-0000-000000000001', ARRAY['luxury', 'chauffeur', 'tours', 'multilingual'], '{"instagram": "https://instagram.com/islanddrivemallorca"}'),
('Calvia Cab', 'Local taxi and transfer service covering all of Calvia municipality. Fixed rates to airport, Palma, and popular destinations. Pre-booking available via WhatsApp.', '+34 699 123 456', NULL, 'Calvia area', 'Calvia Village', '$', false, 'b4000000-0000-0000-0000-000000000001', ARRAY['taxi', 'local', 'fixed-rate', 'whatsapp'], NULL),

-- Grocery & Delivery
('Eroski City Palmanova', 'Well-stocked supermarket in the heart of Palmanova. Fresh produce, bakery, deli counter, and international products section. Open daily until 21:30.', '+34 971 234 567', 'https://eroski.es', 'Avenida de la Playa 15, Palmanova', 'Palmanova', '$', false, 'b4000000-0000-0000-0000-000000000002', ARRAY['supermarket', 'groceries', 'fresh-produce', 'bakery'], NULL),
('Mercadona Santa Ponsa', 'Large supermarket with excellent fresh fish counter, meat section, and wide range of Spanish products. Parking available. Online ordering for home delivery.', '+34 971 345 678', 'https://mercadona.es', 'Carrer de Ramon de Montcada 8, Santa Ponsa', 'Santa Ponsa', '$', false, 'b4000000-0000-0000-0000-000000000002', ARRAY['supermarket', 'delivery', 'spanish-products', 'parking'], NULL),
('Mallorca Fresh Delivery', 'Premium grocery delivery service. Local organic fruit and veg, artisan bread, fresh seafood, and gourmet products delivered to your door same day. Villa provisioning service.', '+34 622 345 678', 'https://mallorcafresh.com', 'Delivers across Calvia', 'Portals Nous', '$$', true, 'b4000000-0000-0000-0000-000000000002', ARRAY['delivery', 'organic', 'villa-provisioning', 'gourmet'], '{"instagram": "https://instagram.com/mallorcafresh"}'),
('Froiz Magaluf', 'Neighbourhood supermarket with good selection of everyday essentials, frozen goods, and household items. Competitive prices. Open 7 days a week.', '+34 971 456 789', 'https://froiz.com', 'Carrer de Torrenova 22, Magaluf', 'Magaluf', '$', false, 'b4000000-0000-0000-0000-000000000002', ARRAY['supermarket', 'groceries', 'everyday', 'affordable'], NULL),

-- Natural & Organic Shops
('BioMallorca', 'Specialist organic and natural products store. Organic fruit and veg, superfoods, natural cosmetics, eco cleaning products, and gluten-free range. Knowledgeable staff.', '+34 971 567 890', 'https://biomallorca.es', 'Calle Mayor 12, Santa Ponsa', 'Santa Ponsa', '$$', true, 'b4000000-0000-0000-0000-000000000004', ARRAY['organic', 'natural', 'superfoods', 'gluten-free', 'eco'], '{"instagram": "https://instagram.com/biomallorca"}'),
('Herbolario Verde', 'Traditional herbalist and health food shop. Wide range of supplements, herbal remedies, essential oils, and natural skincare. Personalised health consultations available.', '+34 971 678 901', NULL, 'Carrer del Puig Major 5, Calvia Village', 'Calvia Village', '$$', false, 'b4000000-0000-0000-0000-000000000004', ARRAY['herbalist', 'supplements', 'essential-oils', 'natural-skincare'], NULL),
('EcoVida Portals', 'Modern eco-conscious shop offering zero-waste products, organic groceries, reusable lifestyle goods, and locally made artisan foods. Refill station for cleaning products.', '+34 699 234 567', NULL, 'Puerto Portals, Local 28', 'Portals Nous', '$$', false, 'b4000000-0000-0000-0000-000000000004', ARRAY['zero-waste', 'organic', 'eco', 'refill', 'artisan'], '{"instagram": "https://instagram.com/ecovidaportals"}'),

-- Eye Care
('Optica Calvia', 'Full-service opticians offering eye exams, designer frames, and contact lenses. Latest lens technology including progressive and blue-light filtering. Quick turnaround on prescriptions.', '+34 971 789 012', 'https://opticacalvia.com', 'Carrer Major 18, Calvia Village', 'Calvia Village', '$$', true, 'b5000000-0000-0000-0000-000000000002', ARRAY['optician', 'glasses', 'contact-lenses', 'eye-exam'], NULL),
('Vision Plus Santa Ponsa', 'Modern optometry practice with advanced eye testing equipment. Specialises in children''s eye care and sports vision. Wide selection of sunglasses and prescription eyewear.', '+34 971 890 123', 'https://visionplus.es', 'Avenida Rey Jaime I 45, Santa Ponsa', 'Santa Ponsa', '$$', false, 'b5000000-0000-0000-0000-000000000002', ARRAY['optometry', 'children', 'sports-vision', 'sunglasses'], NULL),
('Clinica Ocular Palmanova', 'Specialist eye clinic offering comprehensive eye health checks, glaucoma screening, and referrals for laser surgery. Multilingual ophthalmologists on staff.', '+34 971 901 234', 'https://clinicaocular.es', 'Paseo del Mar 7, Palmanova', 'Palmanova', '$$$', false, 'b5000000-0000-0000-0000-000000000002', ARRAY['ophthalmologist', 'eye-clinic', 'glaucoma', 'multilingual'], NULL),

-- Pediatric Care
('Clinica Infantil Calvia', 'Dedicated children''s health clinic with experienced paediatricians. Vaccinations, developmental check-ups, and childhood illness treatment. English, Spanish, and German spoken.', '+34 971 012 345', 'https://clinicainfantilcalvia.es', 'Carrer de Sa Vinya 8, Santa Ponsa', 'Santa Ponsa', '$$', true, 'b5000000-0000-0000-0000-000000000003', ARRAY['paediatrician', 'vaccinations', 'children', 'multilingual'], NULL),
('Dr. Sofia Martinez - Pediatrics', 'Private paediatrician offering personalised care for children from newborn to 16 years. Home visits available. Specialises in allergies and respiratory conditions.', '+34 654 012 345', NULL, 'Consulta Medica, Portals Nous', 'Portals Nous', '$$$', false, 'b5000000-0000-0000-0000-000000000003', ARRAY['private-paediatrician', 'home-visits', 'allergies', 'newborn'], NULL),
('Centro Pediatrico Poniente', 'Family-friendly pediatric centre with on-site lab for quick blood tests. Evening and weekend appointments available. Partners with major international health insurers.', '+34 971 123 456', 'https://centropediatrico.es', 'Avenida de Magaluf 30, Magaluf', 'Magaluf', '$$', false, 'b5000000-0000-0000-0000-000000000003', ARRAY['pediatric-centre', 'lab', 'insurance', 'evening-appointments'], NULL),

-- Boutiques & Fashion
('Marina Boutique', 'Curated selection of Mediterranean resort wear for women. Linen dresses, swimwear, handmade jewellery, and artisan accessories. New collections every season.', '+34 971 234 890', NULL, 'Puerto Portals, Local 12', 'Portals Nous', '$$$', true, 'b6000000-0000-0000-0000-000000000003', ARRAY['resort-wear', 'swimwear', 'jewellery', 'women'], '{"instagram": "https://instagram.com/marinaboutique"}'),
('Calvia Menswear', 'Smart casual and formal menswear. Italian and Spanish brands. Tailoring service available. Suits, shirts, linen trousers, and quality leather goods.', '+34 971 345 901', NULL, 'Calle del Comercio 6, Santa Ponsa', 'Santa Ponsa', '$$$', false, 'b6000000-0000-0000-0000-000000000003', ARRAY['menswear', 'tailoring', 'italian', 'formal'], NULL),
('Sol Kids', 'Children''s clothing boutique with playful European brands. Sizes from newborn to 14 years. Swimwear, casual wear, and occasion outfits. Gift wrapping service.', '+34 971 456 012', NULL, 'Avenida Rey Jaime I 22, Santa Ponsa', 'Santa Ponsa', '$$', false, 'b6000000-0000-0000-0000-000000000003', ARRAY['children', 'kids-clothing', 'european-brands', 'swimwear'], '{"instagram": "https://instagram.com/solkidsmallorca"}'),
('Isla Style', 'Bohemian and contemporary fashion for women. Mix of independent designers and well-known brands. Bags, scarves, sunglasses, and statement pieces.', '+34 634 567 123', NULL, 'Paseo Calvia 9, Palmanova', 'Palmanova', '$$', false, 'b6000000-0000-0000-0000-000000000003', ARRAY['bohemian', 'contemporary', 'accessories', 'women'], '{"instagram": "https://instagram.com/islastyle"}'),
('Portals Designer Outlet', 'Pre-owned luxury fashion at accessible prices. Authenticated designer bags, watches, and clothing from top European houses. Consignment service available.', '+34 971 567 234', 'https://portalsoutlet.com', 'Puerto Portals, Local 35', 'Portals Nous', '$$$$', false, 'b6000000-0000-0000-0000-000000000003', ARRAY['designer', 'luxury', 'pre-owned', 'consignment'], NULL),

-- Language Academies
('Academia de Idiomas Calvia', 'Established language school offering Spanish, English, and German courses. All levels from beginner to advanced. Small group classes, private tuition, and intensive courses. DELE exam preparation.', '+34 971 678 345', 'https://academiacalvia.es', 'Calle del Colegio 4, Calvia Village', 'Calvia Village', '$$', true, 'b7000000-0000-0000-0000-000000000002', ARRAY['spanish', 'english', 'german', 'DELE', 'intensive'], NULL),
('SpeakEasy Mallorca', 'Modern conversational language learning. Small groups meeting in cafes and outdoor settings. Focus on practical, real-life Spanish for expats. Also offering Catalan basics.', '+34 644 789 012', 'https://speakeasymallorca.com', 'Various locations across Calvia', 'Santa Ponsa', '$', false, 'b7000000-0000-0000-0000-000000000002', ARRAY['conversational', 'spanish-for-expats', 'catalan', 'outdoor'], '{"instagram": "https://instagram.com/speakeasymallorca"}'),
('Goethe Zentrum Mallorca', 'German language and cultural centre. Courses for all levels, children''s German classes, and cultural events. Recognised certificates. Also offers translation services.', '+34 971 890 456', 'https://goethemallorca.com', 'Avenida de la Playa 20, Palmanova', 'Palmanova', '$$', false, 'b7000000-0000-0000-0000-000000000002', ARRAY['german', 'children', 'cultural', 'translation', 'certificates'], NULL),

-- Pool & Garden (additional)
('AquaCare Mallorca', 'Professional pool maintenance and cleaning service. Weekly contracts, one-off cleans, and pool opening/closing for the season. Chemical balancing and equipment repairs.', '+34 666 234 567', 'https://aquacaremallorca.com', 'Covers all Calvia', 'Santa Ponsa', '$$', true, 'b9000000-0000-0000-0000-000000000001', ARRAY['pool-maintenance', 'cleaning', 'chemicals', 'seasonal'], NULL),
('Jardineria Verde', 'Complete garden design and maintenance service. Lawn care, irrigation installation, tree pruning, and Mediterranean planting schemes. Regular maintenance contracts available.', '+34 671 345 678', NULL, 'Covers all Calvia', 'Calvia Village', '$$', false, 'b9000000-0000-0000-0000-000000000001', ARRAY['landscaping', 'lawn-care', 'irrigation', 'tree-pruning'], NULL),
('Pool Tech Balear', 'Pool construction, renovation, and technical services. Pump and filter replacements, heating installation, and salt chlorination systems. Emergency call-outs.', '+34 699 456 789', 'https://pooltechbalear.com', 'Covers all Calvia', 'Palmanova', '$$$', false, 'b9000000-0000-0000-0000-000000000001', ARRAY['pool-construction', 'renovation', 'heating', 'emergency'], NULL),
('Mallorca Garden Design', 'Award-winning garden designers creating Mediterranean outdoor living spaces. Terraces, outdoor kitchens, lighting, and drought-resistant planting. Full project management.', '+34 622 567 890', 'https://mallorcagardendesign.com', 'Available across Calvia', 'Bendinat', '$$$$', false, 'b9000000-0000-0000-0000-000000000001', ARRAY['garden-design', 'outdoor-kitchen', 'lighting', 'terrace'], '{"instagram": "https://instagram.com/mallorcagardendesign"}')

ON CONFLICT DO NOTHING;
